export enum ErrorCode {
    // User
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    EMAIL_OR_PHONE_REQUIRED = 'EMAIL_OR_PHONE_REQUIRED',
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
    USER_NOT_IN_COMPANY = 'USER_NOT_IN_COMPANY',
    USER_INACTIVE_IN_COMPANY = 'USER_INACTIVE_IN_COMPANY',
  
    // Auth
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
  
    // Validation
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  
    // Generic
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    COMPANY_CONTEXT_REQUIRED = 'COMPANY_CONTEXT_REQUIRED',
    COMPANY_ACCESS_DENIED = 'COMPANY_ACCESS_DENIED',
    COMPANY_SLUG_ALREADY_EXISTS = 'COMPANY_SLUG_ALREADY_EXISTS',
    UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
    COMPANY_CNPJ_ALREADY_EXISTS = 'COMPANY_CNPJ_ALREADY_EXISTS'
  }
  