export enum ErrorCode {
    // User
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    EMAIL_OR_PHONE_REQUIRED = 'EMAIL_OR_PHONE_REQUIRED',
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  
    // Auth
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
  
    // Validation
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  
    // Generic
    INTERNAL_ERROR = 'INTERNAL_ERROR',
  }
  